version: '3.7'

services:
    postgres:
        container_name: 'postgres'
        image: postgres:latest
        restart: always
        ports:
          - "5430:5432"
        environment:
            POSTGRES_DB: smart_journal
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: mydb
    students-system:
        container_name: 'students-system'
        build:
          context: ./
          dockerfile: Dockerfile
        depends_on:
          - postgres
        ports:
          - "8200:80"
    att-payments:
        container_name: 'att-payments'
        build:
          context: ./
          dockerfile: AttPaym.Dockerfile
        depends_on:
          - postgres
          - students-system
        ports:
          - "8202:80"
        


