version: '3'

services:
    postgres:
        container_name: 'postgres'
        image: postgres:latest
        restart: always
        ports:
          - "5430:5432"
        environment:
            POSTGRES_DB: smart_journal
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: mydb
    students-system:
        container_name: 'students-system'
        image: students-system
        build:
          context: ./
          dockerfile: Dockerfile
        depends_on:
          - postgres
        ports:
          - "8200:80"
    frontend:
        container_name: 'frontend'
        image: frontend
        build:
          context: ./Frontend
          dockerfile: Dockerfile
        depends_on:
          - postgres
          - students-system
        ports:
          - "8100:80"
    balancer:
        container_name: 'balancer'
        image: balancer
        build:
          context: ./
          dockerfile: Nginx.Dockerfile
        depends_on:
          - postgres
          - students-system
          - frontend
        ports:
          - "80:80"