version: '3'

services:
    students-system:
        container_name: 'students-system'
        image: students-system
        build:
          context: ./
          dockerfile: Dockerfile
        ports:
          - "8200:80"
        volumes:
          - "./logs:/app/build/logs:rw"
    frontend:
        container_name: 'frontend'
        image: frontend
        build:
          context: ./Frontend
          dockerfile: Dockerfile
        depends_on:
          - students-system
        ports:
          - "8100:80"
    balancer:
        container_name: 'balancer'
        image: balancer
        build:
          context: ./
          dockerfile: Nginx.Dockerfile
        depends_on:
          - students-system
          - frontend
        ports:
          - "80:80"